name: RandomTP
main: com.gmail.theposhogamer.RandomTP
version: 1.0
author: AnyOD
commands:
   rtp:
      description: Shows info of the plugin RandomTP.
      usage: /<command>
      aliases: [randomtp, randomteleport, rt]