main: com.gmail.theposhogamer.RandomTP
name: RandomTP-Reborn
version: 1.6
softdepend: [Factions, MassiveCore, Vault, PreciousStones]
loadbefore: [Factions, MassiveCore, Vault, PreciousStones] 
author: ThePoshoGamer
commands:
   randomtp:
      description: Basic RandomTP command.
      usage: /<command>
      aliases: [rtp, randomteleport, tprandom]