main: com.gmail.theposhogamer.RandomTP
name: RandomTP-Reborn
version: 1.7
softdepend: [Factions, MassiveCore, Vault, PreciousStones, Kingdoms]
loadbefore: [Factions, MassiveCore, Vault, PreciousStones, Kingdoms] 
author: ThePoshoGamer
commands:
   randomtp:
      description: Basic RandomTP command.
      usage: /<command>
      aliases: [rtp, randomteleport, tprandom]